### ISSUE TITLE
Gem maintenance

### ISSUE THREAD

**Issue by aristofun** [dankimio/tinkoff#2]
Привет, если не планируешь поддержку и развитие гема, дай пожалуйста права на гем tinkoff мне

https://guides.rubygems.org/command-reference/#gem-owner

мэйл: mbutlitsky@gmail.com

**Comment by dankimio** [comment]
Привет! Можешь сделать пул-реквест, новую версию выложу.

**Comment by aristofun** [comment]
Неудобно будет делать и тебя дергать каждый раз, чтобы заюзать. Лучше если ты активно давно не пилишь, чтобы мы оба могли комитить как минимум, а если ты не собираешься развивать, то мне продолжать начатое дело.

**Comment by dankimio** [comment]
@aristofun Добавил в репо

**Comment by aristofun** [comment]
Спасибо. ПОпозже все смерджу. Но исходный вопрос не потерял актуальности — мне гем-то паблишить тоже надо иметь возможность на рубигемс :)

**Comment by aristofun** [comment]
Там просто добавить можно еще одного овнера для этого
